### ISSUE TITLE
/warp <name> <player> command does not work

### ISSUE THREAD

**Issue by Dakir22** [masagameplay/MaSuiteWarps#3]
Hi I am using MaSuite on my 1.14.4 paperspigot server and have just tried to teleport a player with /warp <name> <player> to a warp. However, if I enter this in the paperspigot console, the following error occurs in the console of the proxy.

Does MaSuite work at all already in 1.14.4 or does only version 1.13 work so far?
I am using the latest dev builds of the MaSuite plugins.

**Error:**
`[12:44:50 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@3390cb6c, receiver=Dakir), cancelled=false, tag=BungeeCord) to listener fi.matiaspaavilainen.masuitewarps.bungee.MaSuiteWarps@5c65fa69
java.lang.NullPointerException: null
        at fi.matiaspaavilainen.masuitewarps.bungee.commands.Teleport.warpPlayer(Teleport.java:79) ~[?:?]
        at fi.matiaspaavilainen.masuitewarps.bungee.commands.Teleport.warp(Teleport.java:54) ~[?:?]
        at fi.matiaspaavilainen.masuitewarps.bungee.MaSuiteWarps.onPluginMessage(MaSuiteWarps.java:111) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:433) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:264) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

**Comment by masagameplay** [comment]
Thank you for reporting this. Just to clarify: does warping other players work if you execute the command as a player?

**Comment by Dakir22** [comment]
Yes that works

**Comment by Dakir22** [comment]
No can do either. Same error in the console.

**Comment by masagameplay** [comment]
I cannot reproduce this issue with the latest Paper and the latest Waterfall. Make sure that you have the latest version of MaSuite plugins in both Paper and Bungee.

**Comment by Dakir22** [comment]
Just downloaded the latest builds of Waterfall, Paper 1.14.4 and all MaSuite plugins (Core, Homes, Portals, Teleports, Warps). Unfortunately, the same error still occurs.

Is it possible that this error is caused by another plugin on my server?
Or can the reason be that the test server is running on my Windows 10 computer?

**Comment by masagameplay** [comment]
If you could list the plugins it would be nice but I am 99% sure that is not the reason. I am also running my test server on W10 computer.

**Comment by Dakir22** [comment]
Plugins on Waterfall: https://pastebin.com/7DvKFpZ9
Plugins on Paper: https://pastebin.com/a7MSicHe

But I also have the problem that the Homes GUI doesn't work for me. If the Home GUI is activated in the Config and a player enters the /homes command, this error occurs in the console of the Paperspigot server:
<details>
  <summary>ERROR</summary>
  [14:26:34 WARN]: [MaSuiteHomes] Plugin MaSuiteHomes v1.2.9.4 generated an exception while executing task 21519
java.lang.NullPointerException: null
        at fi.matiaspaavilainen.masuitecore.bukkit.gui.MaSuiteGUI.register(MaSuiteGUI.java:192) ~[?:?]
        at fi.matiaspaavilainen.masuitecore.bukkit.gui.MaSuiteGUI.<init>(MaSuiteGUI.java:60) ~[?:?]
        at fi.matiaspaavilainen.masuitecore.bukkit.gui.MaSuiteGUI.<init>(MaSuiteGUI.java:39) ~[?:?]
        at fi.matiaspaavilainen.masuitehomes.bukkit.commands.GUICommand.lambda$onCommand$0(GUICommand.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-152]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-152]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
</details>

I thought so far that 1.14.4 is the problem because it might not be fully supported yet.

**Comment by masagameplay** [comment]
The plugins should not affect anything but when it comes to Homes GUI, you should disable it until I figure out the nice way of doing that.

**Comment by Dakir22** [comment]
> 
> 
> I cannot reproduce this issue with the latest Paper and the latest Waterfall. Make sure that you have the latest version of MaSuite plugins in both Paper and Bungee.

Which spigot/paper version did you use? The pom.xml file still uses spigot and bungeecord 1.13. http://prntscr.com/omwzgv

Already tried it on a Linux server, but didn't work either.

**Comment by Dakir22** [comment]
Hey I just tested it, so the error only comes when you enter the "/warp <warpname> <spieler>" command in the console. As a player you can warp another player without any problems

**Comment by Dakir22** [comment]
Can you reproduce the error if you enter the command in the cosnole?

**Comment by masagameplay** [comment]
I am currently not at home but I can test later today.

**Comment by masagameplay** [comment]
After testing and trying different ways to reproduce this error I could not get any errors.

**Comment by Dakir22** [comment]
Okay, that's weird. I will try it again in a few days on an empty server without other plugins and with an empty database. I will inform you then.
